spring.application.name=SubAuth-Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.http.converters.preferred-json-mapper=gson